WITH SUM_SALE AS 
(SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS 'SUM_AMOUNT'
FROM OFFLINE_SALE
GROUP BY 1)
SELECT P.PRODUCT_CODE, SUM(P.PRICE * S.SUM_AMOUNT) AS 'SALES'
FROM PRODUCT P 
JOIN SUM_SALE S 
ON P.PRODUCT_ID = S.PRODUCT_ID 
GROUP BY 1
ORDER BY SALES DESC, P.PRODUCT_CODE;
