SELECT A.ITEM_ID AS 'ITEM_ID', A.ITEM_NAME AS 'ITEM_NAME', A.RARITY AS 'RARITY'
FROM ITEM_INFO I 
JOIN ITEM_TREE T ON I.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO A ON T.ITEM_ID = A.ITEM_ID
WHERE I.RARITY LIKE 'RARE'
ORDER BY ITEM_ID DESC;