-- 코드를 작성해주세요
SELECT E.ID, E.GENOTYPE, (SELECT GENOTYPE FROM ECOLI_DATA WHERE ID = E.PARENT_ID) AS PARENT_GENOTYPE
FROM ECOLI_DATA E
WHERE E.GENOTYPE & (SELECT GENOTYPE FROM ECOLI_DATA WHERE ID = E.PARENT_ID) >= (SELECT GENOTYPE FROM ECOLI_DATA WHERE ID = E.PARENT_ID)
ORDER BY ID;