-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME AS 'FISH_NAME', A.LENGTH AS 'LENGTH'
FROM FISH_INFO A
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE= B.FISH_TYPE
WHERE A.LENGTH IN 
    (SELECT MAX(C.LENGTH) FROM FISH_INFO C WHERE C.FISH_TYPE =A.FISH_TYPE 
     GROUP BY C.FISH_TYPE ) -- 물고기 종류별 가장 큰 물고기 찾기
     AND A.LENGTH IS NOT NULL
ORDER BY ID;