-- 코드를 작성해주세요
WITH SUM_SCORE AS 
(SELECT SUM(SCORE) AS 'SCORE', EMP_NO
 FROM HR_GRADE 
 WHERE YEAR = 2022
 GROUP BY EMP_NO
 )
SELECT G.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL 
FROM HR_EMPLOYEES E 
JOIN SUM_SCORE G 
ON E.EMP_NO = G.EMP_NO 
WHERE G.SCORE IN(SELECT MAX(SCORE) FROM SUM_SCORE);